version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core:v4.36.0
    container_name: v2ray
    environment:
      - v2ray.vmess.aead.forced=false
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./log/v2ray:/var/log/v2ray
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8888:8888"

  caddy:
    image: caddy
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./log/caddy:/var/log/caddy
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "443:443"